name: root
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - numpy
  - pandas
  - netcdf4
  - matplotlib
  - cartopy
  - pip:
    - git+https://github.com/raphaeldussin/sectionate.git
